
import { Item, Role, Champion } from './types';

export const GOLD_VALUES = {
  AD: 35, AP: 20, Armor: 20, MR: 20, HP: 2.67, AH: 50, Mana: 1.4, AS: 25, Crit: 40, MS_Flat: 12, MS_Percent: 80, HSP: 68.75
};

export const CHAMPIONS: Champion[] = [
  // TOP
  { name: 'Aatrox', role: Role.TOP, baseBuild: ['Black Cleaver', 'Sundered Sky'] },
  { name: 'Akali', role: Role.TOP, baseBuild: ['Stormsurge', 'Shadowflame'] },
  { name: 'Ambessa', role: Role.TOP, baseBuild: ['Black Cleaver', 'Sundered Sky'] },
  { name: 'Aurora', role: Role.TOP, baseBuild: ['Liandry\'s Torment', 'Stormsurge'] },
  { name: 'Camille', role: Role.TOP, baseBuild: ['Trinity Force', 'Sundered Sky'] },
  { name: 'Cassiopeia', role: Role.TOP, baseBuild: ['Liandry\'s Torment', 'Rylai\'s Crystal Scepter'] },
  { name: 'Cho\'Gath', role: Role.TOP, baseBuild: ['Sunfire Aegis', 'Heartsteel'] },
  { name: 'Darius', role: Role.TOP, baseBuild: ['Stridebreaker', 'Black Cleaver'] },
  { name: 'Dr. Mundo', role: Role.TOP, baseBuild: ['Heartsteel', 'Sunfire Aegis'] },
  { name: 'Fiora', role: Role.TOP, baseBuild: ['Ravenous Hydra', 'Trinity Force'] },
  { name: 'Gangplank', role: Role.TOP, baseBuild: ['Trinity Force', 'The Collector'] },
  { name: 'Garen', role: Role.TOP, baseBuild: ['Stridebreaker', 'Phantom Dancer'] },
  { name: 'Gnar', role: Role.TOP, baseBuild: ['Trinity Force', 'Black Cleaver'] },
  { name: 'Gragas', role: Role.TOP, baseBuild: ['Lich Bane', 'Stormsurge'] },
  { name: 'Gwen', role: Role.TOP, baseBuild: ['Nashor\'s Tooth', 'Shadowflame'] },
  { name: 'Heimerdinger', role: Role.TOP, baseBuild: ['Liandry\'s Torment', 'Rylai\'s Crystal Scepter'] },
  { name: 'Illaoi', role: Role.TOP, baseBuild: ['Black Cleaver', 'Sundered Sky'] },
  { name: 'Irelia', role: Role.TOP, baseBuild: ['Blade of the Ruined King', 'Wit\'s End'] },
  { name: 'Jax', role: Role.TOP, baseBuild: ['Trinity Force', 'Sundered Sky'] },
  { name: 'Jayce', role: Role.TOP, baseBuild: ['The Collector', 'Manamune'] },
  { name: 'K\'Sante', role: Role.TOP, baseBuild: ['Iceborn Gauntlet', 'Sunfire Aegis'] },
  { name: 'Kayle', role: Role.TOP, baseBuild: ['Nashor\'s Tooth', 'Wit\'s End'] },
  { name: 'Kennen', role: Role.TOP, baseBuild: ['Stormsurge', 'Shadowflame'] },
  { name: 'Kled', role: Role.TOP, baseBuild: ['Profane Hydra', 'Black Cleaver'] },
  { name: 'Malphite', role: Role.TOP, baseBuild: ['Sunfire Aegis', 'Thornmail'] },
  { name: 'Maokai', role: Role.TOP, baseBuild: ['Sunfire Aegis', 'Thornmail'] },
  { name: 'Mordekaiser', role: Role.TOP, baseBuild: ['Rylai\'s Crystal Scepter', 'Liandry\'s Torment'] },
  { name: 'Nasus', role: Role.TOP, baseBuild: ['Trinity Force', 'Frozen Heart'] },
  { name: 'Olaf', role: Role.TOP, baseBuild: ['Ravenous Hydra', 'Stridebreaker'] },
  { name: 'Ornn', role: Role.TOP, baseBuild: ['Sunfire Aegis', 'Thornmail'] },
  { name: 'Pantheon', role: Role.TOP, baseBuild: ['Sundered Sky', 'Black Cleaver'] },
  { name: 'Poppy', role: Role.TOP, baseBuild: ['Sunfire Aegis', 'Iceborn Gauntlet'] },
  { name: 'Quinn', role: Role.TOP, baseBuild: ['The Collector', 'Infinity Edge'] },
  { name: 'Renekton', role: Role.TOP, baseBuild: ['Black Cleaver', 'Stridebreaker'] },
  { name: 'Riven', role: Role.TOP, baseBuild: ['Black Cleaver', 'Sundered Sky'] },
  { name: 'Rumble', role: Role.TOP, baseBuild: ['Liandry\'s Torment', 'Shadowflame'] },
  { name: 'Ryze', role: Role.TOP, baseBuild: ['Archangel\'s Staff', 'Rod of Ages'] },
  { name: 'Sejuani', role: Role.TOP, baseBuild: ['Sunfire Aegis', 'Thornmail'] },
  { name: 'Sett', role: Role.TOP, baseBuild: ['Stridebreaker', 'Black Cleaver'] },
  { name: 'Shen', role: Role.TOP, baseBuild: ['Sunfire Aegis', 'Titanic Hydra'] },
  { name: 'Singed', role: Role.TOP, baseBuild: ['Rylai\'s Crystal Scepter', 'Liandry\'s Torment'] },
  { name: 'Sion', role: Role.TOP, baseBuild: ['Sunfire Aegis', 'Titanic Hydra'] },
  { name: 'Smolder', role: Role.TOP, baseBuild: ['Trinity Force', 'Manamune'] },
  { name: 'Tahm Kench', role: Role.TOP, baseBuild: ['Heartsteel', 'Sunfire Aegis'] },
  { name: 'Teemo', role: Role.TOP, baseBuild: ['Nashor\'s Tooth', 'Liandry\'s Torment'] },
  { name: 'Tryndamere', role: Role.TOP, baseBuild: ['Kraken Slayer', 'Infinity Edge'] },
  { name: 'Udyr', role: Role.TOP, baseBuild: ['Liandry\'s Torment', 'Sunfire Aegis'] },
  { name: 'Urgot', role: Role.TOP, baseBuild: ['Black Cleaver', 'Stridebreaker'] },
  { name: 'Vayne', role: Role.TOP, baseBuild: ['Blade of the Ruined King', 'Kraken Slayer'] },
  { name: 'Volibear', role: Role.TOP, baseBuild: ['Iceborn Gauntlet', 'Nashor\'s Tooth'] },
  { name: 'Warwick', role: Role.TOP, baseBuild: ['Titanic Hydra', 'Stridebreaker'] },
  { name: 'Wukong', role: Role.TOP, baseBuild: ['Trinity Force', 'Sundered Sky'] },
  { name: 'Yasuo', role: Role.TOP, baseBuild: ['Kraken Slayer', 'Infinity Edge'] },
  { name: 'Yone', role: Role.TOP, baseBuild: ['Kraken Slayer', 'Infinity Edge'] },
  { name: 'Yorick', role: Role.TOP, baseBuild: ['Trinity Force', 'Serylda\'s Grudge'] },
  { name: 'Zac', role: Role.TOP, baseBuild: ['Sunfire Aegis', 'Thornmail'] },

  // JUNGLE
  { name: 'Amumu', role: Role.JUNGLE, baseBuild: ['Sunfire Aegis', 'Thornmail'] },
  { name: 'Bel\'Veth', role: Role.JUNGLE, baseBuild: ['Kraken Slayer', 'Stridebreaker'] },
  { name: 'Briar', role: Role.JUNGLE, baseBuild: ['Sundered Sky', 'Black Cleaver'] },
  { name: 'Diana', role: Role.JUNGLE, baseBuild: ['Nashor\'s Tooth', 'Lich Bane'] },
  { name: 'Ekko', role: Role.JUNGLE, baseBuild: ['Lich Bane', 'Stormsurge'] },
  { name: 'Elise', role: Role.JUNGLE, baseBuild: ['Lich Bane', 'Stormsurge'] },
  { name: 'Evelynn', role: Role.JUNGLE, baseBuild: ['Stormsurge', 'Shadowflame'] },
  { name: 'Fiddlesticks', role: Role.JUNGLE, baseBuild: ['Liandry\'s Torment', 'Shadowflame'] },
  { name: 'Graves', role: Role.JUNGLE, baseBuild: ['The Collector', 'Black Cleaver'] },
  { name: 'Hecarim', role: Role.JUNGLE, baseBuild: ['Black Cleaver', 'Stridebreaker'] },
  { name: 'Ivern', role: Role.JUNGLE, baseBuild: ['Ardent Censer', 'Moonstone Renewer'] },
  { name: 'Jarvan IV', role: Role.JUNGLE, baseBuild: ['Sundered Sky', 'Black Cleaver'] },
  { name: 'Karthus', role: Role.JUNGLE, baseBuild: ['Liandry\'s Torment', 'Shadowflame'] },
  { name: 'Kayn', role: Role.JUNGLE, baseBuild: ['Profane Hydra', 'Serylda\'s Grudge'] },
  { name: 'Kha\'Zix', role: Role.JUNGLE, baseBuild: ['Profane Hydra', 'The Collector'] },
  { name: 'Kindred', role: Role.JUNGLE, baseBuild: ['Kraken Slayer', 'The Collector'] },
  { name: 'Lee Sin', role: Role.JUNGLE, baseBuild: ['Sundered Sky', 'Black Cleaver'] },
  { name: 'Lillia', role: Role.JUNGLE, baseBuild: ['Liandry\'s Torment', 'Rylai\'s Crystal Scepter'] },
  { name: 'Master Yi', role: Role.JUNGLE, baseBuild: ['Kraken Slayer', 'Blade of the Ruined King'] },
  { name: 'Nidalee', role: Role.JUNGLE, baseBuild: ['Stormsurge', 'Lich Bane'] },
  { name: 'Nocturne', role: Role.JUNGLE, baseBuild: ['Stridebreaker', 'Black Cleaver'] },
  { name: 'Nunu & Willump', role: Role.JUNGLE, baseBuild: ['Sunfire Aegis', 'Thornmail'] },
  { name: 'Rammus', role: Role.JUNGLE, baseBuild: ['Thornmail', 'Sunfire Aegis'] },
  { name: 'Rek\'Sai', role: Role.JUNGLE, baseBuild: ['Stridebreaker', 'Black Cleaver'] },
  { name: 'Rengar', role: Role.JUNGLE, baseBuild: ['Profane Hydra', 'The Collector'] },
  { name: 'Shaco', role: Role.JUNGLE, baseBuild: ['Profane Hydra', 'The Collector'] },
  { name: 'Shyvana', role: Role.JUNGLE, baseBuild: ['Liandry\'s Torment', 'Nashor\'s Tooth'] },
  { name: 'Skarner', role: Role.JUNGLE, baseBuild: ['Heartsteel', 'Sunfire Aegis'] },
  { name: 'Taliyah', role: Role.JUNGLE, baseBuild: ['Luden\'s Companion', 'Shadowflame'] },
  { name: 'Trundle', role: Role.JUNGLE, baseBuild: ['Trinity Force', 'Ravenous Hydra'] },
  { name: 'Vi', role: Role.JUNGLE, baseBuild: ['Sundered Sky', 'Black Cleaver'] },
  { name: 'Viego', role: Role.JUNGLE, baseBuild: ['Kraken Slayer', 'Sundered Sky'] },
  { name: 'Warwick', role: Role.JUNGLE, baseBuild: ['Titanic Hydra', 'Stridebreaker'] },
  { name: 'Xin Zhao', role: Role.JUNGLE, baseBuild: ['Sundered Sky', 'Black Cleaver'] },

  // MID
  { name: 'Ahri', role: Role.MID, baseBuild: ["Luden's Companion", 'Shadowflame'] },
  { name: 'Anivia', role: Role.MID, baseBuild: ['Rod of Ages', 'Liandry\'s Torment'] },
  { name: 'Annie', role: Role.MID, baseBuild: ['Stormsurge', 'Shadowflame'] },
  { name: 'Aurelion Sol', role: Role.MID, baseBuild: ['Rylai\'s Crystal Scepter', 'Liandry\'s Torment'] },
  { name: 'Azir', role: Role.MID, baseBuild: ['Nashor\'s Tooth', 'Shadowflame'] },
  { name: 'Cassiopeia', role: Role.MID, baseBuild: ['Archangel\'s Staff', 'Liandry\'s Torment'] },
  { name: 'Fizz', role: Role.MID, baseBuild: ['Lich Bane', 'Stormsurge'] },
  { name: 'Hwei', role: Role.MID, baseBuild: ["Luden's Companion", 'Shadowflame'] },
  { name: 'Kassadin', role: Role.MID, baseBuild: ['Archangel\'s Staff', 'Rod of Ages'] },
  { name: 'Katarina', role: Role.MID, baseBuild: ['Nashor\'s Tooth', 'Lich Bane'] },
  { name: 'LeBlanc', role: Role.MID, baseBuild: ['Stormsurge', 'Shadowflame'] },
  { name: 'Lissandra', role: Role.MID, baseBuild: ['Stormsurge', 'Shadowflame'] },
  { name: 'Lux', role: Role.MID, baseBuild: ["Luden's Companion", 'Shadowflame'] },
  { name: 'Malzahar', role: Role.MID, baseBuild: ['Liandry\'s Torment', 'Rylai\'s Crystal Scepter'] },
  { name: 'Naafiri', role: Role.MID, baseBuild: ['Profane Hydra', 'The Collector'] },
  { name: 'Orianna', role: Role.MID, baseBuild: ["Luden's Companion", 'Shadowflame'] },
  { name: 'Qiyana', role: Role.MID, baseBuild: ['Profane Hydra', 'The Collector'] },
  { name: 'Sylas', role: Role.MID, baseBuild: ['Lich Bane', 'Stormsurge'] },
  { name: 'Syndra', role: Role.MID, baseBuild: ["Luden's Companion", 'Shadowflame'] },
  { name: 'Talon', role: Role.MID, baseBuild: ['Profane Hydra', 'The Collector'] },
  { name: 'Twisted Fate', role: Role.MID, baseBuild: ['Lich Bane', 'Rapid Firecannon'] },
  { name: 'Veigar', role: Role.MID, baseBuild: ['Stormsurge', 'Shadowflame'] },
  { name: 'Vel\'Koz', role: Role.MID, baseBuild: ['Liandry\'s Torment', 'Shadowflame'] },
  { name: 'Vex', role: Role.MID, baseBuild: ["Luden's Companion", 'Shadowflame'] },
  { name: 'Viktor', role: Role.MID, baseBuild: ["Luden's Companion", 'Shadowflame'] },
  { name: 'Vladimir', role: Role.MID, baseBuild: ['Liandry\'s Torment', 'Shadowflame'] },
  { name: 'Zed', role: Role.MID, baseBuild: ['Profane Hydra', 'The Collector'] },
  { name: 'Zoe', role: Role.MID, baseBuild: ['Stormsurge', 'Lich Bane'] },

  // ADC
  { name: 'Aphelios', role: Role.ADC, baseBuild: ['The Collector', 'Infinity Edge'] },
  { name: 'Ashe', role: Role.ADC, baseBuild: ['Kraken Slayer', 'Trinity Force'] },
  { name: 'Caitlyn', role: Role.ADC, baseBuild: ['The Collector', 'Infinity Edge'] },
  { name: 'Draven', role: Role.ADC, baseBuild: ['The Collector', 'Infinity Edge'] },
  { name: 'Ezreal', role: Role.ADC, baseBuild: ['Trinity Force', 'Manamune'] },
  { name: 'Jhin', role: Role.ADC, baseBuild: ['The Collector', 'Infinity Edge'] },
  { name: 'Jinx', role: Role.ADC, baseBuild: ['Kraken Slayer', 'Infinity Edge'] },
  { name: 'Kai\'Sa', role: Role.ADC, baseBuild: ['Kraken Slayer', 'Guinsoo\'s Rageblade'] },
  { name: 'Kalista', role: Role.ADC, baseBuild: ['Blade of the Ruined King', 'Guinsoo\'s Rageblade'] },
  { name: 'Kog\'Maw', role: Role.ADC, baseBuild: ['Blade of the Ruined King', 'Guinsoo\'s Rageblade'] },
  { name: 'Lucian', role: Role.ADC, baseBuild: ['Kraken Slayer', 'The Collector'] },
  { name: 'Miss Fortune', role: Role.ADC, baseBuild: ['The Collector', 'Infinity Edge'] },
  { name: 'Nilah', role: Role.ADC, baseBuild: ['The Collector', 'Infinity Edge'] },
  { name: 'Samira', role: Role.ADC, baseBuild: ['The Collector', 'Infinity Edge'] },
  { name: 'Sivir', role: Role.ADC, baseBuild: ['Kraken Slayer', 'Infinity Edge'] },
  { name: 'Tristana', role: Role.ADC, baseBuild: ['Kraken Slayer', 'Infinity Edge'] },
  { name: 'Twitch', role: Role.ADC, baseBuild: ['Blade of the Ruined King', 'Hurricane'] },
  { name: 'Varus', role: Role.ADC, baseBuild: ['Blade of the Ruined King', 'Guinsoo\'s Rageblade'] },
  { name: 'Vayne', role: Role.ADC, baseBuild: ['Blade of the Ruined King', 'Kraken Slayer'] },
  { name: 'Xayah', role: Role.ADC, baseBuild: ['Kraken Slayer', 'Infinity Edge'] },
  { name: 'Zeri', role: Role.ADC, baseBuild: ['Kraken Slayer', 'Infinity Edge'] },

  // SUPPORT
  { name: 'Alistar', role: Role.SUPPORT, baseBuild: ['Locket of the Iron Solari', 'Zeke\'s Convergence'] },
  { name: 'Bard', role: Role.SUPPORT, baseBuild: ['Locket of the Iron Solari', 'Zeke\'s Convergence'] },
  { name: 'Blitzcrank', role: Role.SUPPORT, baseBuild: ['Locket of the Iron Solari', 'Zeke\'s Convergence'] },
  { name: 'Braum', role: Role.SUPPORT, baseBuild: ['Locket of the Iron Solari', 'Zeke\'s Convergence'] },
  { name: 'Janna', role: Role.SUPPORT, baseBuild: ['Moonstone Renewer', 'Ardent Censer'] },
  { name: 'Karma', role: Role.SUPPORT, baseBuild: ['Ardent Censer', 'Staff of Flowing Water'] },
  { name: 'Leona', role: Role.SUPPORT, baseBuild: ['Locket of the Iron Solari', 'Zeke\'s Convergence'] },
  { name: 'Lulu', role: Role.SUPPORT, baseBuild: ['Ardent Censer', 'Staff of Flowing Water'] },
  { name: 'Lux', role: Role.SUPPORT, baseBuild: ['Luden\'s Companion', 'Shadowflame'] },
  { name: 'Milio', role: Role.SUPPORT, baseBuild: ['Moonstone Renewer', 'Ardent Censer'] },
  { name: 'Morgana', role: Role.SUPPORT, baseBuild: ['Liandry\'s Torment', 'Rylai\'s Crystal Scepter'] },
  { name: 'Nami', role: Role.SUPPORT, baseBuild: ['Imperial Mandate', 'Staff of Flowing Water'] },
  { name: 'Nautilus', role: Role.SUPPORT, baseBuild: ['Locket of the Iron Solari', 'Zeke\'s Convergence'] },
  { name: 'Pyke', role: Role.SUPPORT, baseBuild: ['The Collector', 'Umbral Glaive'] },
  { name: 'Rakan', role: Role.SUPPORT, baseBuild: ['Locket of the Iron Solari', 'Zeke\'s Convergence'] },
  { name: 'Renata Glasc', role: Role.SUPPORT, baseBuild: ['Ardent Censer', 'Staff of Flowing Water'] },
  { name: 'Senna', role: Role.SUPPORT, baseBuild: ['Umbral Glaive', 'Kraken Slayer'] },
  { name: 'Seraphine', role: Role.SUPPORT, baseBuild: ['Ardent Censer', 'Staff of Flowing Water'] },
  { name: 'Sona', role: Role.SUPPORT, baseBuild: ['Ardent Censer', 'Staff of Flowing Water'] },
  { name: 'Soraka', role: Role.SUPPORT, baseBuild: ['Moonstone Renewer', 'Ardent Censer'] },
  { name: 'Taric', role: Role.SUPPORT, baseBuild: ['Locket of the Iron Solari', 'Zeke\'s Convergence'] },
  { name: 'Thresh', role: Role.SUPPORT, baseBuild: ['Locket of the Iron Solari', 'Zeke\'s Convergence'] },
  { name: 'Yuumi', role: Role.SUPPORT, baseBuild: ['Moonstone Renewer', 'Ardent Censer'] },
  { name: 'Zilean', role: Role.SUPPORT, baseBuild: ['Shurelya\'s Battlesong', 'Ardent Censer'] },
  { name: 'Zyra', role: Role.SUPPORT, baseBuild: ['Liandry\'s Torment', 'Rylai\'s Crystal Scepter'] },
];

export const ITEMS: Item[] = [
  { id: 'collector', name: 'The Collector', cost: 3000, stats: { ad: 50, crit: 25 }, passiveValue: 300, description: 'Death and Taxes: Execute enemies below 5% health on hit. Grants bonus gold on kill.', isRift: true, isARAM: true },
  { id: 'kraken', name: 'Kraken Slayer', cost: 3000, stats: { ad: 45, as: 40, ms_percent: 4 }, passiveValue: 500, description: 'Bring It Down: Every third basic attack deals bonus physical damage, increasing against the same target.', isRift: true, isARAM: true },
  { id: 'ie', name: 'Infinity Edge', cost: 3450, stats: { ad: 65, crit: 25 }, passiveValue: 400, description: 'Perfection: Increases Critical Strike Damage by 40%. The ultimate force multiplier.', isRift: true, isARAM: true },
  { id: 'ludens', name: "Luden's Companion", cost: 2750, stats: { ap: 100, mana: 600, ah: 10 }, passiveValue: 590, description: 'Fire: Gain Shots periodically. Damaging abilities consume all Shots to deal bonus magic damage to the target and nearby enemies.', isRift: true, isARAM: true },
  { id: 'blackcleaver', name: 'Black Cleaver', cost: 3000, stats: { ad: 40, hp: 400, ah: 20 }, passiveValue: 500, description: 'Carve: Dealing physical damage to an enemy reduces their Armor by 6% for 6s (max 30%). Fervor: Dealing physical damage grants Move Speed.', isRift: true, isARAM: true },
  { id: 'stormsurge', name: 'Stormsurge', cost: 2800, stats: { ap: 90, ms_percent: 6 }, passiveValue: 467, description: 'Stormraider: Dealing 35% of a champion\'s max HP within 3s applies Squall, dealing magic damage and granting gold on kill.', isRift: true, isARAM: true },
  { id: 'deathcap', name: "Rabadon's Deathcap", cost: 3500, stats: { ap: 130 }, passiveValue: 0, description: 'Magical Opus: Increases your total Ability Power by 35%. The absolute peak of arcane potential.', isRift: true, isARAM: true },
  { id: 'profane', name: 'Profane Hydra', cost: 2850, stats: { ad: 55, ah: 10 }, passiveValue: 540, description: 'Cleave: Attacks deal physical damage to nearby enemies. Heretical Slash (Active): Deal physical damage to nearby enemies, increased against low health targets.', isRift: true, isARAM: true },
  { id: 'trinity', name: 'Trinity Force', cost: 3333, stats: { ad: 45, as: 33, hp: 300, ah: 20 }, passiveValue: 600, description: 'Spellblade: After using an ability, your next attack deals bonus physical damage. Threefold Strike: Attacks grant Move Speed.', isRift: true, isARAM: true },
  { id: 'sundered', name: 'Sundered Sky', cost: 3100, stats: { ad: 45, hp: 450, ah: 15 }, passiveValue: 400, description: 'Lightshield Strike: The first attack against a champion critically strikes and heals you for a percentage of missing health.', isRift: true, isARAM: true },
  { id: 'liandrys', name: "Liandry's Torment", cost: 3000, stats: { ap: 90, hp: 300 }, passiveValue: 450, description: 'Torment: Dealing ability damage burns enemies for max health magic damage over 3s. Suffering: Gain increased damage against champions while in combat.', isRift: true, isARAM: true },
  { id: 'rylais', name: "Rylai's Crystal Scepter", cost: 2600, stats: { ap: 75, hp: 400 }, passiveValue: 200, description: 'Rimefrost: Damaging abilities slow enemies by 30% for 1s. Tactical movement suppression.', isRift: true, isARAM: true },
  { id: 'serylda', name: "Serylda's Grudge", cost: 3000, stats: { ad: 45, ah: 20 }, passiveValue: 350, description: 'Rancor: Gain Armor Penetration based on Lethality. Bitter Cold: Damaging abilities slow enemies below 50% HP.', isRift: true, isARAM: true },
  { id: 'shadowflame', name: 'Shadowflame', cost: 3200, stats: { ap: 120 }, passiveValue: 400, description: 'Cinderbloom: Magic damage and true damage critically strike enemies below 35% health.', isRift: true, isARAM: true },
  { id: 'voidstaff', name: 'Void Staff', cost: 3000, stats: { ap: 80 }, passiveValue: 400, description: 'Dissolve: Grants 40% Magic Penetration. The primary response to high MR targets.', isRift: true, isARAM: true },
  { id: 'mortalreminder', name: 'Mortal Reminder', cost: 3000, stats: { ad: 40, crit: 25 }, passiveValue: 300, description: 'Sepsis: Dealing physical damage applies 40% Grievous Wounds. grants 35% Armor Penetration.', isRift: true, isARAM: true },
];
